---
title: "Change Log"
---

## Overview

This page lists versions of my documents and the corresponding changes. 


::: {.file-card}
[Research Document](../pages/manuscript.qmd)

| Version | Date | Updates |
| ----- | ----- | ----- |
| 2.5.6 | August 19, 2026 | Removed `ambiguity_type` and `prior_rt` from Experiment 2 statistical models. Changed uses of *participant* to *subject* for consistency. |
| 2.5.5 | August 16, 2026 | Added subsection 3.5.3 presenting the hierarchical cognitive information increment. This metric had been inadvertently dropped from the capstone project but it is necessary for justification of the surrogate used in the pCI-Gradient Ascent document. |
| 2.5.4 | August 16, 2026 | Clarified (in Section 4.4.5. Computational Semantic Measures) the numbering of the two sentence frames used for calculating BERT cosine distance between the context embeddings and subject heading embeddings in Experiment 2. This now aligns with Section 4.4.6. Dependent and Independent Variables.  |
| 2.5.3 | August 13, 2026 | Minor edits to theory chapter and Section 3.4 |
| 2.5.2 | August 12, 2026 | Added a paragraph to the lit review chapter pointing towards the new section "Information-Theoretic Accounts of Category Structure in Cognitive Science" in the theoretical framework chapter |
| 2.5.1 | August 11, 2026 | Expanded Maximum Entropy portion of Section 3.3: H3 as a Mathematical Consequence of the CI Framework |

: {tbl-colwidths="[15,15,70]"}

:::




::: {.file-card}
[pCI-Gradient Ascent](../pages/gradient-ascent.qmd)

| Version | Date | Updates |
| ----- | ----- | ----- |
| 1.1 | August 17, 2026 | The introduction reintroduces the structural and pointwise cognitive information metrics ($\mathrm{CI_{struct}(d)}$ and pCI) and introduces pointwise structural cognitive information. A footnote explains that the unmarked notation pCI is retained throughout for readability and should be read as  $\mathrm{pCI^{struct}}$
| 1.0 | August 16, 2026 | Initial posting of document |

: {tbl-colwidths="[15,15,70]"}

:::


::: {.file-card}
[Supplementary Material](../pages/background.qmd)

| Version | Date | Updates |
| ----- | ----- | ----- |
| 1.1.3 | September 6. 2026 | Added Conditional Mutual Information section |
| 1.1.2 | September 4, 2026 | Added "Relationship Between Entropy and Mutual Information" section |
| 1.1.1 | September 3, 2026 | Clarified between averaged and pointwise conditional entropy |
| 1.1 | September 3, 2026 | Added sections on relative entropy and mutual information |
| 1.0 | September 3, 2026 | Initial posting of document |

: {tbl-colwidths="[15,15,70]"}

:::


::: {.file-card}
**Website**

| Date | Update |
| ----- | ----- |
| September 3, 2026 | Added [supplementary material page](../pages/background.qmd) for more extensive discussion of technical details |
| August 27, 2026 | I realized that *Psychological Review* articles are behind a paywall and I have thus replaced PDF versions of Trott and Bergen (2023) with links to that article's site. I'm not happy about this, either. |
| August 25, 2026 | Updated [profile page](../pages/profile.qmd) to include a hierarchy that maps the intellectual scaffolding of my research program |
| August 24, 2026 | Added [roadmap webpage](../pages/roadmap.qmd) which lists planned updates to my research documents and website |


: {tbl-colwidths="[30,70]"}

:::